name: face-recognition-server

networks:
  face-infra:
    external: true

services:
  app:
    build: .
    env_file: .env
    ports:
      - "8001:8000"
    networks:
      - face-infra
    volumes:
      - ./models:/app/models
    restart: unless-stopped
    extra_hosts:
      - "host.docker.internal:host-gateway"  # Linux compatibility
